// Code generated by protoc-gen-go.
// source: ib/common.proto
// DO NOT EDIT!

/*
Package ib is a generated protocol buffer package.

It is generated from these files:
	ib/common.proto

It has these top-level messages:
	WireMessage
*/
package ib

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type WireMessage struct {
	WireVersion      *int32  `protobuf:"varint,1,req,name=wire_version" json:"wire_version,omitempty"`
	InterfaceName    *string `protobuf:"bytes,2,req,name=interface_name" json:"interface_name,omitempty"`
	InterfaceVersion *int32  `protobuf:"varint,3,req,name=interface_version" json:"interface_version,omitempty"`
	MessageType      *string `protobuf:"bytes,4,req,name=message_type" json:"message_type,omitempty"`
	MessageData      []byte  `protobuf:"bytes,5,req,name=message_data" json:"message_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *WireMessage) Reset()         { *m = WireMessage{} }
func (m *WireMessage) String() string { return proto.CompactTextString(m) }
func (*WireMessage) ProtoMessage()    {}

func (m *WireMessage) GetWireVersion() int32 {
	if m != nil && m.WireVersion != nil {
		return *m.WireVersion
	}
	return 0
}

func (m *WireMessage) GetInterfaceName() string {
	if m != nil && m.InterfaceName != nil {
		return *m.InterfaceName
	}
	return ""
}

func (m *WireMessage) GetInterfaceVersion() int32 {
	if m != nil && m.InterfaceVersion != nil {
		return *m.InterfaceVersion
	}
	return 0
}

func (m *WireMessage) GetMessageType() string {
	if m != nil && m.MessageType != nil {
		return *m.MessageType
	}
	return ""
}

func (m *WireMessage) GetMessageData() []byte {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func init() {
}
