// Code generated by protoc-gen-go.
// source: ib/mutex/v1/messages.proto
// DO NOT EDIT!

/*
Package ib_mutex_v1 is a generated protocol buffer package.

It is generated from these files:
	ib/mutex/v1/messages.proto

It has these top-level messages:
	Request
	Response
	Release
*/
package ib_mutex_v1

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Request struct {
	Requestor        *string `protobuf:"bytes,1,req,name=requestor" json:"requestor,omitempty"`
	OwnerName        *string `protobuf:"bytes,2,req,name=owner_name" json:"owner_name,omitempty"`
	Resource         *string `protobuf:"bytes,3,req,name=resource" json:"resource,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

func (m *Request) GetRequestor() string {
	if m != nil && m.Requestor != nil {
		return *m.Requestor
	}
	return ""
}

func (m *Request) GetOwnerName() string {
	if m != nil && m.OwnerName != nil {
		return *m.OwnerName
	}
	return ""
}

func (m *Request) GetResource() string {
	if m != nil && m.Resource != nil {
		return *m.Resource
	}
	return ""
}

type Response struct {
	Request           *Request `protobuf:"bytes,1,req,name=request" json:"request,omitempty"`
	ReleaseToken      *string  `protobuf:"bytes,2,opt,name=release_token" json:"release_token,omitempty"`
	WasObtained       *bool    `protobuf:"varint,3,req,name=was_obtained" json:"was_obtained,omitempty"`
	ObtainedAbandoned *bool    `protobuf:"varint,4,req,name=obtained_abandoned" json:"obtained_abandoned,omitempty"`
	XXX_unrecognized  []byte   `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func (m *Response) GetRequest() *Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Response) GetReleaseToken() string {
	if m != nil && m.ReleaseToken != nil {
		return *m.ReleaseToken
	}
	return ""
}

func (m *Response) GetWasObtained() bool {
	if m != nil && m.WasObtained != nil {
		return *m.WasObtained
	}
	return false
}

func (m *Response) GetObtainedAbandoned() bool {
	if m != nil && m.ObtainedAbandoned != nil {
		return *m.ObtainedAbandoned
	}
	return false
}

type Release struct {
	Token            *string `protobuf:"bytes,1,req,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Release) Reset()         { *m = Release{} }
func (m *Release) String() string { return proto.CompactTextString(m) }
func (*Release) ProtoMessage()    {}

func (m *Release) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func init() {
}
