// Code generated by protoc-gen-go.
// source: ib/converterService/v1/messages.proto
// DO NOT EDIT!

/*
Package ib_converterService_v1 is a generated protocol buffer package.

It is generated from these files:
	ib/converterService/v1/messages.proto

It has these top-level messages:
	Request
	Notification
*/
package ib_converterService_v1

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Request struct {
	Site             *string `protobuf:"bytes,1,req,name=site" json:"site,omitempty"`
	Batch            *string `protobuf:"bytes,2,req,name=batch" json:"batch,omitempty"`
	Sample           *string `protobuf:"bytes,3,req,name=sample" json:"sample,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

func (m *Request) GetSite() string {
	if m != nil && m.Site != nil {
		return *m.Site
	}
	return ""
}

func (m *Request) GetBatch() string {
	if m != nil && m.Batch != nil {
		return *m.Batch
	}
	return ""
}

func (m *Request) GetSample() string {
	if m != nil && m.Sample != nil {
		return *m.Sample
	}
	return ""
}

type Notification struct {
	Success          *bool    `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Request          *Request `protobuf:"bytes,2,req,name=request" json:"request,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}

func (m *Notification) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *Notification) GetRequest() *Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func init() {
}
