// Code generated by protoc-gen-go.
// source: ib/housekeeper/v1/messages.proto
// DO NOT EDIT!

/*
Package ib_housekeeper_v1 is a generated protocol buffer package.

It is generated from these files:
	ib/housekeeper/v1/messages.proto

It has these top-level messages:
	BatchLoaded
*/
package ib_housekeeper_v1

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type BatchLoaded struct {
	Site             *string `protobuf:"bytes,1,req,name=site" json:"site,omitempty"`
	BatchName        *string `protobuf:"bytes,2,req,name=batch_name" json:"batch_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BatchLoaded) Reset()         { *m = BatchLoaded{} }
func (m *BatchLoaded) String() string { return proto.CompactTextString(m) }
func (*BatchLoaded) ProtoMessage()    {}

func (m *BatchLoaded) GetSite() string {
	if m != nil && m.Site != nil {
		return *m.Site
	}
	return ""
}

func (m *BatchLoaded) GetBatchName() string {
	if m != nil && m.BatchName != nil {
		return *m.BatchName
	}
	return ""
}

func init() {
}
